### ISSUE TITLE
Skill

### ISSUE THREAD

**Issue by nekowinston** [sgoudham/dotfiles#1]
that should be the first issue

alright, that was a dumb thing to do for a screenshot, sorry. I'll close the issue :laughing:

**Comment by sgoudham** [comment]
No. It stays open.
![gigachad](https://user-images.githubusercontent.com/58985301/199176797-a2c12b62-8a97-4f51-9091-ed4ec5212b82.gif)

**Comment by backwardspy** [comment]
![image](https://github.com/sgoudham/dotfiles/assets/289746/dcc6c66f-97e4-4de8-b486-9568efa2c005)
